// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Static information about the running backend.
 */
export type AppInfo = { protocolVersion: number, appVersion: string, os: string, arch: string, 
/**
 * Scans bypass permission checks because the app was started as
 * administrator or root. The app never elevates itself.
 */
privilegedAccess: boolean, };
