// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Moves selected files and folders (folders with everything in them) to
 * the Recycle Bin (Windows) or Trash (macOS, Linux). Nothing is ever
 * deleted permanently. Refused unless deleting was allowed in this run of
 * the app, and while the scan is running.
 */
export type DeleteRequest = { generation: number, nodes: Array<number>, };
