// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeleteFailure } from "./DeleteFailure";

/**
 * What a delete did. Deleted items are removed from the scan, which moves
 * to a new revision.
 */
export type DeleteReport = { generation: number, 
/**
 * Items now gone from disk and from the scan.
 */
deleted: Array<number>, 
/**
 * Of those, items that were already gone before the delete.
 */
alreadyGone: number, failed: Array<DeleteFailure>, 
/**
 * Totals of the deleted items, as scanned.
 */
files: number, logical: number, allocated: number, };
