// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeleteMode } from "./DeleteMode";

/**
 * Deletes selected files and folders (folders with everything in them).
 * Refused while the scan is running.
 */
export type DeleteRequest = { generation: number, nodes: Array<number>, mode: DeleteMode, };
