// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metric } from "./Metric";

/**
 * Asks for the treemap of `view` at the given size. The binary reply is
 * described in [`wire`].
 */
export type LayoutRequest = { generation: number, 
/**
 * Echoed in the reply so the interface can drop stale replies.
 */
request: number, view: number, metric: Metric, 
/**
 * CSS pixels.
 */
width: number, height: number, };
