// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Crumb } from "./Crumb";
import type { FolderState } from "./FolderState";

/**
 * Everything the details panel shows about one node.
 */
export type NodeDetails = { generation: number, node: number, name: string, path: string, 
/**
 * `None` for files.
 */
folder: FolderState | null, logical: number, 
/**
 * Known allocated bytes. For a file, `None` means unknown.
 */
allocated: number | null, unknownAllocationFiles: number, files: number, cloud: boolean, hardlinked: boolean, 
/**
 * For a hard-link alias, the path that owns the allocation.
 */
aliasOf: string | null, 
/**
 * From the scan root down to and including this node.
 */
ancestors: Array<Crumb>, };
