// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OmissionReason } from "./OmissionReason";
import type { OmissionSample } from "./OmissionSample";

export type OmissionGroup = { reason: OmissionReason, 
/**
 * Skipped by policy (links, mounts, special files) rather than an error.
 */
policy: boolean, count: number, samples: Array<OmissionSample>, };
