// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returned when a scan starts.
 */
export type ScanStarted = { generation: number, root: string, };
