// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OmissionGroup } from "./OmissionGroup";
import type { ScanPhase } from "./ScanPhase";

/**
 * A coalesced snapshot of one scan, emitted as [`SCAN_STATUS_EVENT`].
 */
export type ScanStatus = { generation: number, 
/**
 * The scan root as displayed to the user.
 */
root: string, phase: ScanPhase, elapsedMs: number, files: number, dirs: number, logical: number, allocated: number, unknownAllocationFiles: number, hardlinkAliases: number, pendingDirs: number, 
/**
 * Changes whenever the scanned tree changes.
 */
revision: number, omissions: Array<OmissionGroup>, };
