// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScanPhase = { "kind": "scanning" } | { "kind": "complete" } | { "kind": "completeWithOmissions" } | { "kind": "cancelled" } | { "kind": "failed", message: string, };
