// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metric } from "./Metric";

/**
 * Asks for a page of matching files, largest first by `metric`.
 */
export type SearchResultsRequest = { generation: number, search: number, metric: Metric, offset: number, limit: number, };
