// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchRow } from "./SearchRow";

export type SearchPage = { generation: number, search: number, offset: number, 
/**
 * Matching files in all.
 */
total: number, rows: Array<SearchRow>, };
