// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Totals for the files matching a filename search, across the whole scan.
 */
export type SearchSummary = { generation: number, 
/**
 * Identifies this query within the scan; newer queries get larger
 * numbers. Layout and result requests name it.
 */
search: number, query: string, files: number, logical: number, 
/**
 * Known, owned allocation of matching files.
 */
allocated: number, unknownAllocationFiles: number, };
