// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchRow = { node: number, name: string, 
/**
 * The containing folder.
 */
parent: number, 
/**
 * The containing folder's path relative to the scan root; empty at the
 * root.
 */
folder: string, logical: number, 
/**
 * `None` when unknown. Hard-link aliases report 0 (see `alias`).
 */
allocated: number | null, 
/**
 * Another name of a hard-linked file whose allocation is counted at its
 * first name.
 */
alias: boolean, };
