// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectedItem } from "./SelectedItem";

/**
 * The items a selection stands for: entries inside another selected folder
 * are counted once, with that folder.
 */
export type SelectionSummary = { generation: number, 
/**
 * Selected items not inside another selected folder.
 */
items: number, folders: number, 
/**
 * Files in the items, counting each folder's contents.
 */
files: number, logical: number, allocated: number, unknownAllocationFiles: number, 
/**
 * Entries left out because they're no longer in the scan.
 */
missing: number, 
/**
 * The largest items, at most [`SELECTION_SAMPLES`].
 */
samples: Array<SelectedItem>, };
