// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Asks what an action on a set of selected items would touch.
 */
export type SelectionRequest = { generation: number, nodes: Array<number>, };
