// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SelectedItem = { node: number, name: string, path: string, folder: boolean, logical: number, 
/**
 * Known allocated bytes. For a file, `None` means unknown.
 */
allocated: number | null, 
/**
 * Files at or under this item.
 */
files: number, };
