// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SmallItem } from "./SmallItem";

/**
 * Items of a small-items region, largest first.
 */
export type SmallItemsPage = { generation: number, folder: number, offset: number, total: number, items: Array<SmallItem>, 
/**
 * Other children of the folder with no size in this metric, which the
 * map never draws.
 */
empty: number, };
