// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metric } from "./Metric";

/**
 * Asks for the items merged into an "other small items" region: the
 * region's folder and item count, as drawn with this metric and search.
 */
export type SmallItemsRequest = { generation: number, folder: number, count: number, metric: Metric, search: number | null, offset: number, limit: number, };
