// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SmallItem = { node: number, name: string, folder: boolean, 
/**
 * Size in the requested metric (matching bytes when filtered).
 */
weight: number, };
