// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Capacity of the volume holding the scan root, for the volume overview.
 */
export type VolumeInfo = { generation: number, 
/**
 * The scan root is the volume's top folder, so the scan covers the
 * whole volume. The overview is only offered then.
 */
isRoot: boolean, capacity: number, free: number, filesystem: string | null, 
/**
 * Filesystem structures that could be measured (the NTFS master file
 * table, when elevated).
 */
metadata: number | null, };
